version: '3'
services:
  puzzle:
    env_file: .env
    ports:
      - 8080:80
    build: ./puzzle
    volumes: 
      - "./puzzle/src/Puzzle:/usr/Puzzle"
    command: bash -c "dotnet restore Puzzle.csproj && dotnet run Puzzle.csproj"
  consul:
    image: consul