version: '3'
services:
  consul:
    image: consul
    ports:
      - 8500:8500
  db:
    env_file: .env
    image: postgres:9.6.3-alpine
  puzzle:
    env_file: .env
    ports:
      - 8080:80
    build: ./puzzle
    volumes: 
      - "./puzzle/src/Puzzle:/usr/Puzzle"
    command: bash -c "dotnet restore Puzzle.csproj && dotnet run Puzzle.csproj"

networks:
  micro:
    